---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # initContainers:
      # - images: mysql:5.7
      #   name: seed-data
      #   volumeMounts:
      #   - name: mysql-persistent-storage
      #     mountPath: /var/lib/mysql
      #   env:
      #     # Use secret in real usage
      #   - name: MYSQL_ROOT_PASSWORD
      #     value: password


      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: testdata
          mountPath: /tmp/testdata
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: testdata
        persistentVolumeClaim:
          claimName: testdata-pv-claim
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql
# spec:
#   selector:
#     matchLabels:
#       app: mysql
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       initContainers:
#       - images: mysql:5.7
#         name: seed-data
#         volumeMounts:
#         - name: mysql-persistent-storage
#           mountPath: /var/lib/mysql
#         env:
#           # Use secret in real usage
#         - name: MYSQL_ROOT_PASSWORD
#           value: password


#       containers:
#       - image: mysql:5.7
#         name: mysql
#         env:
#           # Use secret in real usage
#         - name: MYSQL_ROOT_PASSWORD
#           value: password
#         ports:
#         - containerPort: 3306
#           name: mysql
#         volumeMounts:
#         - name: mysql-persistent-storage
#           mountPath: /var/lib/mysql
#         - name: testdata
#           mountPath: /tmp/testdata
#       volumes:
#       - name: mysql-persistent-storage
#         persistentVolumeClaim:
#           claimName: mysql-pv-claim
#       - name: testdata
#         persistentVolumeClaim:
#           claimName: testdata-pv-claim