apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  # storageClassName: local-storage
  storageClassName: hostpath
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  # local:
  hostPath:
    # path: "/run/desktop/mnt/d/Dev/pingcap/mysql"
    # path: "/mnt/wsl/hostmount/mysql"
    path: "/run/desktop/mnt/wsl/hostmount/mysql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  # storageClassName: local-storage
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: testdata-pv-volume
  labels:
    type: local
spec:
  # storageClassName: local-storage
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # local: 
  hostPath:
    # path: "/run/desktop/mnt/d/Dev/pingcap/test_db"
    # path: "/mnt/wsl/hostmount/test_db"
    path: "/run/desktop/mnt/wsl/hostmount/test_db"
    
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testdata-pv-claim
spec:
  # storageClassName: local-storage
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi