kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.name }}-pvc
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.className }}

